# Generated by Django 3.0.5 on 2020-08-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('commits', models.CharField(max_length=20)),
                ('watch', models.CharField(max_length=20)),
                ('star', models.CharField(max_length=20)),
                ('fork', models.CharField(max_length=20)),
                ('colaboradores', models.CharField(max_length=20)),
                ('fecha_actualizacion', models.CharField(max_length=100)),
                ('nombre_lenguajes', models.CharField(max_length=200)),
                ('url_repositorio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
