# Generated by Django 3.0.5 on 2020-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('repositorios', '0001_initial'), ('repositorios', '0002_auto_20200816_1818'), ('repositorios', '0003_auto_20200817_1732')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('commits', models.CharField(max_length=20, null=True)),
                ('colaboradores', models.CharField(max_length=20, null=True)),
                ('fecha_actualizacion', models.CharField(max_length=100, null=True)),
                ('nombre_lenguajes', models.CharField(max_length=200, null=True)),
                ('url_repositorio', models.CharField(max_length=500, null=True)),
                ('fecha_ult_scraping', models.DateField(auto_now=True)),
            ],
        ),
    ]
