# Generated by Django 3.0.5 on 2020-08-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0001_squashed_0003_auto_20200817_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositorio',
            old_name='fecha_ult_scraping',
            new_name='fecha_scraping',
        ),
    ]
