# Generated by Django 3.0.5 on 2020-08-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='fecha_ult_scraping',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='colaboradores',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='commits',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='fecha_actualizacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='fork',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='nombre_lenguajes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='star',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='titulo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='url_repositorio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='watch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
