# Generated by Django 3.0.5 on 2020-08-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0002_auto_20200816_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='star',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='watch',
        ),
    ]
