# Generated by Django 3.0.5 on 2020-08-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0002_auto_20200817_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='fecha_scraping',
        ),
    ]
