# Generated by Django 3.0.5 on 2020-08-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0004_remove_usuario_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repositorio',
        ),
    ]
