# Generated by Django 3.0.5 on 2020-08-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0006_repositorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repositorio',
        ),
    ]
