# Generated by Django 3.0.5 on 2020-08-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0007_delete_repositorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('star', models.IntegerField(null=True)),
                ('fork', models.IntegerField(null=True)),
                ('fecha_creacion', models.DateField(max_length=100, null=True)),
                ('fecha_actualizacion', models.CharField(max_length=100, null=True)),
                ('url_commits', models.CharField(max_length=500, null=True)),
                ('url_colaboradores', models.CharField(max_length=500, null=True)),
                ('url_lenguajes', models.CharField(max_length=500, null=True)),
                ('url_repositorio', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
